<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearnBank.Application\LearnBank.Application.csproj" />
    <ProjectReference Include="..\LearnBank.Domain\LearnBank.Domain.csproj" />
    <ProjectReference Include="..\LearnBank.Infrastructure\LearnBank.Infrastructure.csproj" />
  </ItemGroup>

</Project>
